"""knowledge-base bootstrap/update for Sprint 15."""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console

from app.config.loader import load_project_registry
from app.logging.audit import write_audit
from app.paths import get_logs_dir, get_workspace_dir


FILES = [
    "00-project-summary.md",
    "01-architecture-map.md",
    "02-feature-index.md",
    "03-current-status.md",
    "04-risk-list.md",
    "05-release-checklist.md",
    "06-next-sprints.md",
]


def _default_content(name: str, project_type: str, root: Path, fname: str) -> str:
    title = fname[:-3].replace("-", " ").title()
    return (
        f"# {name} - {title}\n\n"
        f"- Project: {name}\n"
        f"- Type: {project_type}\n"
        f"- Root: {root}\n\n"
        "_Generated by `knowledge init`; update with real project data._\n"
    )


def knowledge_init(name: str, force: bool = typer.Option(False, "--force", help="Overwrite existing files")) -> None:
    """Create 00-06 knowledge-base files for a project."""
    console = Console()
    reg = load_project_registry()
    project = next((p for p in reg.projects if p.name == name), None)
    if not project:
        console.print(f"[red]Unknown project: {name}[/red]")
        raise typer.Exit(1)
    kb_root = Path(str(project.knowledge)) if project.knowledge else get_workspace_dir() / "knowledge-base" / name
    kb_root.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    skipped: list[Path] = []
    for fname in FILES:
        path = kb_root / fname
        if path.exists() and not force:
            skipped.append(path)
            continue
        path.write_text(_default_content(name, project.type, project.root, fname), encoding="utf-8")
        written.append(path)
    write_audit(
        event="knowledge_init",
        payload={"project": name, "written": [str(x) for x in written], "skipped": [str(x) for x in skipped]},
        logs_root=get_logs_dir(),
    )
    for p in written:
        console.print(f"[green]Wrote[/green] {p}")
    for p in skipped:
        console.print(f"[yellow]Skipped[/yellow] {p}")
